name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This means the workflow will run when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch that will be used to deploy
          folder: .  # The folder where your website files are located (in this case, root)
          clean: true  # This will remove previous files from the gh-pages branch before deploying

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Deploy updated website to GitHub Pages"
